builtins.o: src/builtins.c src/funlisp_internal.h inc/funlisp.h \
 src/iter.h src/ringbuf.h src/hashtable.h
charbuf.o: src/charbuf.c src/charbuf.h
gc.o: src/gc.c src/funlisp_internal.h inc/funlisp.h src/iter.h \
 src/ringbuf.h src/hashtable.h
hashtable.o: src/hashtable.c src/iter.h src/hashtable.h
iter.o: src/iter.c src/iter.h
module.o: src/module.c src/funlisp_internal.h inc/funlisp.h src/iter.h \
 src/ringbuf.h src/hashtable.h
parse.o: src/parse.c src/funlisp_internal.h inc/funlisp.h src/iter.h \
 src/ringbuf.h src/hashtable.h src/charbuf.h
ringbuf.o: src/ringbuf.c src/ringbuf.h
textcache.o: src/textcache.c src/funlisp_internal.h inc/funlisp.h \
 src/iter.h src/ringbuf.h src/hashtable.h
types.o: src/types.c src/funlisp_internal.h inc/funlisp.h src/iter.h \
 src/ringbuf.h src/hashtable.h
util.o: src/util.c src/funlisp_internal.h inc/funlisp.h src/iter.h \
 src/ringbuf.h src/hashtable.h
