; Comparisons: null? eq? equal? ==
(assert-error 'LE_2FEW (null?))
(assert-error 'LE_2FEW (eq?))
(assert-error 'LE_2FEW (eq? 1))
(assert-error 'LE_2FEW (equal?))
(assert-error 'LE_2FEW (equal? 1))

(assert (< 1 2))
(assert (<= 1 2))
(assert (<= 1 1))
(assert (> 2 1))
(assert (>= 2 1))
(assert (>= 1 1))
(assert (= 5 5))
(assert (== 5 5))
(assert (!= 1 3))

(assert (= (+ 1 2 3) 6))
(assert (= (- 5 3) 2))
(assert (= (- 10 1 2) 7))
(assert (= (/ 24 6) 4))
(assert (= (* 4 6) 24))
(assert (= (- (- 5)) 5))

(assert-error 'LE_2FEW (-))
(assert-error 'LE_TYPE (- 'a 1))
(assert-error 'LE_TYPE (- 1 'a))
(assert (= (+) 0))
(assert-error 'LE_TYPE (+ 'a))
; OUTPUT(0)
